#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

show_help() {
    echo "Usage: $0 command"
    echo "Commands:"
    echo "  update    Update the development environment configurations"
    echo "  help      Show this help message. CAN ALSO BE USED AS: '[command] help' for more info on a specific command"
    echo "  add       choose what to add to env (alias, PATH, custom line to .bashrc)"
}

if [ -z "$1" ] || [ "$1" == "update" ]; then
    source "$PATH_DEV_ENV/scripts/dev-env-update-configs"
    exit 0
elif [ -z "$2" ]; then
    if [ "$1" == "help" ]; then
        show_help
        exit 0
    elif [ "$1" == "add" ]; then
        select choice in "Alias" "PATH" "Custom" "Exit"; do
            case $choice in
            Alias)
                add_alias
                break
                ;;
            PATH)
                add_path
                break
                ;;
            Custom)
                add_custom_line
                break
                ;;
            Exit)
                echo "Exiting..."
                ;;
            esac
        done
        exit 0
    elif [ "$1" == "edit" ]; then
        source "$PATH_DEV_ENV/scripts/dev-env-edit-configs"
        exit 0
    fi
elif [ -z "$3" ]; then
    if [ "$1" == "help" ]; then
        if [ "$2" == "help" ]; then
            echo "$0 help hypr: Shows syntax to modify hyprland keybinds."
            echo "$0 help i3: Shows syntax to modify i3wm keybinds."
            echo "$0 help vim: Shows how to exit vim :)"
            exit 0
        elif [ "$2" == "hypr" ]; then
            echo "Find your config file. Likely in ~/.config/hypr/hyprland.conf"
            echo "  Unbind the existing keybind if it is already set using: unbind = SUPER, left"
            echo "  Set a new keybind using (example): bindd = SUPER, H, Move focus left, movefocus, l"
            exit 0
        elif [ "$2" == "i3" ]; then
            echo "Find your config file. Likely in ~/.config/i3/config"
            echo "  Set a new keybind using (example): bindsym $mod+H focus left"
            exit 0
        elif [ "$2" == "vim" ]; then
            echo "How to exit vim/nvim:"
            echo "  Wait holy shit I completely forgot..."
            exit 0
        fi
    elif [ "$1" == "add" ]; then
        if [ "$2" == "help" ]; then
            echo "Usage: $0 add [alias|path|custom]"
            echo "  alias  - Add a new alias to your shell configuration"
            echo "  path   - Add a new path to your PATH environment variable"
            echo "  custom - Add a custom line to your shell configuration"
            exit 0
        elif [ "$2" == "alias" ]; then
            source "$PATH_DEV_ENV/scripts/dev-env-add-alias"
            exit 0
        elif [ "$2" == "path" ]; then
            source "$PATH_DEV_ENV/scripts/dev-env-add-path"
            exit 0
        elif [ "$2" == "custom" ]; then
            source "$PATH_DEV_ENV/scripts/dev-env-add-custom-line"
            exit 0
        fi
    elif [ "$1" == "edit" ]; then
        if [ "$2" == "help" ]; then
            echo "Open the configs for your dev-env in your editor."
            exit 0
        fi
    fi
fi

show_help
exit 1
