#!/bin/bash

renew_nvim_config() {
    if [ -d ~/.config/nvim ]; then
        rm -rf ~/.config/nvim
    fi
    mkdir -p ~/.config
    cp -r "$PATH_DEV_ENV/config/nvim" ~/.config/
    echo -e "${GREEN}nvim config renewed.${NC}"
    # Set up Omarchy hook for theme syncing
    HOOKS_DIR="$HOME/.config/omarchy/hooks"
    if [ -d "$HOOKS_DIR" ]; then
        if [ ! -f "$HOOKS_DIR/theme-set" ]; then
            echo "Creating theme-set hook for Omarchy..."
            cp "$HOOKS_DIR/theme-set.sample" "$HOOKS_DIR/theme-set"
            sudo echo "ln -sf \"\$HOME/.config/omarchy/current/theme/neovim.lua\" \"\$HOME/.config/nvim/lua/plugins/theme.lua\"" >>"$HOOKS_DIR/theme-set"
            echo -e "${GREEN}Omarchy theme-set hook created for nvim.${NC}"
        fi
    fi
}

renew_hypr_config() {
    local HYPR_DIR="$HOME/.config/hypr"

    if [ ! -d "$HYPR_DIR" ]; then
        return
    fi

    local CURR_DIR="$(pwd)"
    local LEFT_BIND_HYPR="bindd = SUPER, H, .*, l"
    local RIGHT_BIND_HYPR="bindd = SUPER, L, .*, r"
    local UP_BIND_HYPR="bindd = SUPER, K, .*, u"
    local DOWN_BIND_HYPR="bindd = SUPER, J, .*, d"

    cd "$HYPR_DIR"

    if ! rg "$LEFT_BIND_HYPR" >/dev/null; then
        echo "$LEFT_BIND_HYPR" >> "$HYPR_DIR/hyprland.conf"
    fi

    if ! rg "$RIGHT_BIND_HYPR" >/dev/null; then
        echo "$RIGHT_BIND_HYPR" >> "$HYPR_DIR/hyprland.conf"
    fi

    if ! rg "$UP_BIND_HYPR" >/dev/null; then
        echo "$UP_BIND_HYPR" >> "$HYPR_DIR/hyprland.conf"
    fi

    if ! rg "$DOWN_BIND_HYPR" >/dev/null; then
        echo "$DOWN_BIND_HYPR" >> "$HYPR_DIR/hyprland.conf"
    fi

    cd "$CURR_DIR"
    echo -e "${GREEN}hypr config renewed.${NC}"
}

renew_nvim_config
renew_hypr_config

