#!/bin/bash

echo "Detecting shell..."
if [ -z "$ZSH_VERSION" ]; then
    shell="zsh"
elif [ -z "$BASH_VERSION" ]; then
    shell="bash"
else
    echo -e "${RED}Unsupported shell. You need either bash or zsh for this.${NC}"
    exit 1
fi
echo "Detected shell: $shell"
