#!/bin/bash

if [ -n "$BASH_VERSINFO" ]; then
    shell="bash"
elif [ -n "$ZSH_VERSION" ]; then
    shell="zsh"
else
    echo -e "${RED}Unsupported shell. You need either bash or zsh for this.${NC}"
    exit 1
fi
